src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RestaurantRepository::class)]
class Restaurant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: 'Le nom du restaurant ne peut pas être vide')]
    #[Assert\Length(
        max: 255,
        maxMessage: 'Le nom du restaurant ne peut pas contenir plus de {{ limit }} caractères.'
    )]
    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Assert\NotBlank(message: "L'adresse du restaurant ne peut pas être vide")]
    #[Assert\Length(
        max: 100,
        maxMessage: "L'adresse du restaurant ne peut pas contenir plus de {{ limit }} caractères."
    )]
    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[Assert\Length(
        max: 255,
        maxMessage: 'La description du restaurant ne peut pas contenir plus de {{ limit }} caractères.',
    )]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $rating = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[Assert\Type(
        type: 'float',
        message: 'Veuillez uniquement saisir des chiffres.',
    )]
    #[Assert\Length(
        max: 5,
        maxMessage: 'Le prix moyen du restaurant ne peut pas contenir plus de {{ limit }} chiffres.',
    )]
    #[Assert\PositiveOrZero(
        message: 'Le prix ne peut pas être négatif.'
    )]
    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[Assert\Length(
        max: 255,
        maxMessage: "L'adresse du site internet du restaurant ne peut pas contenir plus de {{ limit }} caractères.",
    )]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(nullable: true)]
    private ?bool $already_done = null;

    /**
     * @var Collection<int, Food>
     */
    #[ORM\ManyToMany(targetEntity: Food::class, inversedBy: 'restaurants')]
    private Collection $food;

    #[ORM\ManyToOne(inversedBy: 'restaurant')]
    #[ORM\JoinColumn(nullable: false)]
    private ?City $city = null;

    #[Assert\Length(
        min: 0,
        max: 15,
        maxMessage: 'Le numéro de téléphone ne peut pas contenir plus de {{ limit }} caractères.',
    )]
    #[ORM\Column(nullable: true)]
    private ?string $phoneNumber = null;

    /**
     * @var Collection<int, Rating>
     */
    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Rating::class)]
    private Collection $ratings;

    public function __construct()
    {
        $this->food = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getAlreadyDone(): ?bool
    {
        return $this->already_done;
    }

    public function isAlreadyDone(): ?bool
    {
        return $this->already_done;
    }

    public function setAlreadyDone(?bool $already_done): self
    {
        $this->already_done = $already_done;

        return $this;
    }

    /**
     * @return Collection<int, Food>
     */
    public function getFood(): Collection
    {
        return $this->food;
    }

    public function addFood(Food $food): self
    {
        if (!$this->food->contains($food)) {
            $this->food->add($food);
        }

        return $this;
    }

    public function removeFood(Food $food): self
    {
        $this->food->removeElement($food);

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * @return Collection<int, Rating>
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings->add($rating);
            $rating->setRestaurant($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getRestaurant() === $this) {
                $rating->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getAverageRatings(): ?float
    {
        $ratings = 0;
        $i = 0;

        $allRating = $this->getRatings();

        if ($allRating->isEmpty()) {
            return null;
        }

        foreach ($allRating as $value) {
            $note = $value->getRating();
            $ratings += $note;
            ++$i;
        }

        if ($i >= 1) {
            return $ratings / $i;
        }

        return null;
    }
}

templates/addCity.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une ville{% endblock %}

{% block body %}
    <div class="block-page">
        <h1 class="block-name">Ajouter une ville</h1>
        {{ form_start(cityForm, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_widget(cityForm) }}
        <div class="button">
            <button class="btn-add">Ajouter</button>
        </div>
        {{ form_end(cityForm) }}
    </div>
{% endblock %}

templates/addFood.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un type de restauration{% endblock %}

{% block body %}
    <div class="block-page">
        <h1 class="block-name">Ajouter un type de cuisine</h1>
        {{ form_start(foodForm, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_widget(foodForm) }}
        <div class="button">
            <button class="btn-add">Ajouter</button>
        </div>
        {{ form_end(foodForm) }}
        </div>
{% endblock %}

templates/addRating.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notation{% endblock %}

{% block body %}
<div class="block-page">
    <h1 class="block-name">Noter le restaurant</h1>
    <div class="list-one-restaurant">
        <section class="restaurant-list">
            <div class="card">
                <img src="{{ asset('uploads/pictures/' ~ restaurant.picture) }}" class="card-top" alt="">
                <div class="card-body">
                    {% for i in restaurant.getFood %}
                        <div class="restaurant-food">{{ i.name }}</div>
                    {% endfor %}
                    <div class="restaurant-name"> {{ restaurant.name }} </div>
                    <address class="restaurant-address">{{ restaurant.address }}, {{ restaurant.city }} </address>
                    <p class="restaurant-description">{{ restaurant.description }} </p>
                    <div class="restaurant-price">Prix moyen: {{ restaurant.price }}€ </div>
                    <div class="restaurant-rating">
                        {% if restaurant.ratings|length != null %}
                            {% for i in 0..4 %}
                                {% if i<restaurant.averageRatings %}
                                    <img src="{{ asset('build/images/goodStar.png') }}" class="star" alt="">
                                {% else %}
                                    <img src="{{ asset('build/images/badStar.png') }}" class="star" alt="">
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        <div class="restaurant-average-rating">{{ restaurant.averageRatings }}</div>
                        <div class="restaurant-average-rating">{{ 'number_of_ratings'|trans({votes: restaurant.ratings|length}) }}</div>
                        <div class="restaurant-add-rating">
                            <h2>{{ form_start(ratingForm, {'attr': {'novalidate': 'novalidate'}}) }}</h2>
                            <h2>{{ form_widget(ratingForm) }}</h2>
                            <div class="button-rating">
                                <button class="btn-add-rating">Noter</button>
                            </div>
                            <h2>{{ form_end(ratingForm) }}</h2>
                        </div>
                    </div>
                    <div class="restaurant-phone-number">{{ restaurant.phoneNumber }}</div>
                    <a class="restaurant-website">{{ restaurant.website }} </a>
                    <div class="card-button">
                        <a href="{{ path('restaurant_update', {'id':restaurant.id}) }}" class="btn btn-default">Modifier</a>
                        <a href="{{ path('restaurant_delete', {'id':restaurant.id}) }}" class="btn btn-default">Supprimer</a>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock  %}

templates/addRestaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un restaurant{% endblock %}

{% block body %}
    <div class="block-page">
        <h1 class="block-name">Ajouter un restaurant</h1>
        {{ form_start(restaurantForm, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_row(restaurantForm.name) }}
        {{ form_row(restaurantForm.address) }}
        {{ form_row(restaurantForm.description) }}
        {{ form_row(restaurantForm.price) }}
        {{ form_row(restaurantForm.website) }}
        {{ form_row(restaurantForm.already_done) }}
        {{ form_row(restaurantForm.food) }}
        <div>
            <a class="form-redirect" href="{{ path('food_add') }}">Ajouter un type de cuisine</a>
        </div>
        {{ form_row(restaurantForm.city) }}
        <div>
            <a class="form-redirect" href="{{ path('city_add') }}">Ajouter une ville</a>
        </div>
        {{ form_row(restaurantForm.phoneNumber) }}
        {{ form_row(restaurantForm.picture) }}
        <div class="button">
            <button class="btn-add">Ajouter</button>
        </div>
        {{ form_end(restaurantForm) }}
    </div>
{% endblock %}

templates/addUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Se créer un compte{% endblock %}

{% block body %}
    <div class="block-page">
        <h1 class="block-name">Se créer un compte</h1>
        {{ form_start(userForm, {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_widget(userForm) }}
        <div class="button">
            <button class="btn-add">Ajouter</button>
        </div>
        {{ form_end(userForm) }}
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Resto_Verse{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Satisfy&display=swap" rel="stylesheet">
{#
        <meta name="viewport" content="width=device-width, initial-scale=1">
#}
        {% block stylesheets %}{{ encore_entry_link_tags('app') }}{% endblock %}
    </head>
    <body>
        <header>
            {% include('navbar.html.twig') %}
        </header>
        <section>
            <div>
                {% block body %}{% endblock %}
            </div>
        </section>
        <footer>
            {% include('footer.html.twig') %}
        </footer>
    </body>
    <script>
        const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click', ()=> {
            navLinks.classList.toggle('mobile-menu')
        })
    </script>
    {% block javascripts %}{{ encore_entry_script_tags('app') }}{% endblock %}
</html>

templates/footer.html.twig
<footer>
</footer>

templates/listRestaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
{% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="flash flash-{{ label }}">
                {{ message }}
            </div>
        {% endfor%}
    {% endfor %}
    {% include('searchBar.html.twig') %}
    <div class="list-one-restaurant">
        <section class="restaurant-list">
            {% for restaurant in restaurants %}
                <div class="card">
                    <img src="{{ asset('uploads/pictures/' ~ restaurant.picture) }}" class="card-top" alt="">
                    <div class="card-body">
                        {% if restaurant.alreadyDone == true  %}
                            <img src="{{ asset('build/images/alreadyDone.png') }}" class="already-done-img" alt="">
                        {% endif %}
                        {% for i in restaurant.food %}
                           <div class="restaurant-food">{{ i.name }}</div>
                        {% endfor %}
                        <div class="restaurant-name"> {{ restaurant.name }} </div>
                        <address class="restaurant-address">{{ restaurant.address }}, {{ restaurant.city }} </address>
                        <p class="restaurant-description">{{ restaurant.description }} </p>
                        {% if restaurant.price != null %}
                            <div class="restaurant-price">Prix moyen: {{ restaurant.price }}€ </div>
                        {% endif %}
                        <div class="restaurant-rating">
                            {% if restaurant.ratings|length != null %}
                                {% for i in 0..4 %}
                                    {% if i<restaurant.averageRatings %}
                                        <img src="{{ asset('build/images/goodStar.png') }}" class="star" alt="">
                                    {% else %}
                                        <img src="{{ asset('build/images/badStar.png') }}" class="star" alt="">
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        <div class="restaurant-average-rating">{{ restaurant.averageRatings }}</div>
                        <div class="restaurant-average-rating">{{ 'number_of_ratings'|trans({votes: restaurant.ratings|length}) }}</div>
                            <div class="restaurant-add-rating">
                                {% set hasRated = false %}
                                {% for i in restaurant.ratings %}
                                    {% if i.users == app.user %}
                                        {% set hasRated = true %}
                                        <a href="{{ path('rating_update', {'id':restaurant.id}) }}">Modifier sa note</a>
                                    {% endif %}
                                {% endfor %}
                                {% if not hasRated %}
                                    <a href="{{ path('rating_add', {'id': restaurant.id}) }}">Noter le restaurant</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="restaurant-phone-number">{{ restaurant.phoneNumber }}</div>
                        <a class="restaurant-website" href="{{ restaurant.website }}"> {{ restaurant.website }} </a>
                        <div class="card-button">
                            <a href="{{ path('restaurant_update', {'id':restaurant.id}) }}" class="btn btn-default">Modifier</a>
                            <a href="{{ path('restaurant_delete', {'id':restaurant.id}) }}" class="btn btn-default">Supprimer</a>
                        </div>
                        <div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
    </div>
{% endblock  %}

templates/navbar.html.twig
<nav class="navbar">
    <div class="nav-links">
        <ul>
            <li class="active">
                <a class="header_home" href="{{ path('restaurant_list') }}" >Accueil</a>
            </li>
            <li class="" >
                <a class="" href="{{ path('restaurant_add') }}">Ajouter un restaurant</a>
            </li>
            <li class="">
                <a class="" href="{{ path('restaurant_random') }}">Me proposer un restaurant</a>
            </li>

            {% if is_granted ('IS_AUTHENTICATED_FULLY')  %}
                <li class="">
                    <a class="" href="{{ path('user_details', {'id':app.user.id}) }}">Profil</a>
                </li>
            {% else %}

                <li>
                    <a class="" href="{{ path('user_add') }}">Se créer un compte</a>
                </li>
            {% endif %}

        </ul>
    </div>
    <img src="{{ asset('build/images/menu_burger.png') }}" class="menu-hamburger" alt="menu hamburger">
</nav>

templates/randomRestaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant aléatoire{% endblock %}

{% block body %}
<div class="block-page">
    <h1 class="block-name">Restaurant aléatoire</h1>
    <div class="list-one-restaurant">
        <section class="restaurant-list">
            {% for result in results %}
                <div class="card">
                    <img src="{{ asset('uploads/pictures/' ~ result.picture) }}" class="card-top" alt="">
                    <div class="card-body">
                        {% if result.alreadyDone == true  %}
                            <img src="{{ asset('build/images/alreadyDone.png') }}" class="already-done-img" alt="">
                        {% endif %}
                        {% for i in result.getFood %}
                            <div class="restaurant-food">{{ i.name }}</div>
                        {% endfor %}
                        <div class="restaurant-name"> {{ result.name }} </div>
                        <address class="restaurant-address">{{ result.address }}, {{ result.city }} </address>
                        <p class="restaurant-description">{{ result.description }} </p>
                        <div class="restaurant-price">Prix moyen: {{ result.price }}€ </div>
                        <div class="restaurant-rating">
                            {% for i in 0..4 %}
                                {% if i<result.averageRatings %}
                                    <img src="{{ asset('build/images/goodStar.png') }}" class="star" alt="">
                                {% else %}
                                    <img src="{{ asset('build/images/badStar.png') }}" class="star" alt="">
                                {% endif %}
                            {% endfor %}
                            <div>{{ result.ratings|length }} votes</div>
                            <div class="restaurant-add-rating">
                                <a href="{{ path('rating_add', {'id': result.id}) }}">Noter le restaurant</a>
                            </div>
                        </div>
                        <div class="restaurant-phone-number">{{ result.phoneNumber }}</div>
                        <a class="restaurant-website"> {{ result.website }} </a>
                        <div class="card-button">
                            <a href="{{ path('restaurant_update', {'id':result.id}) }}" class="btn btn-default">Modifier</a>
                            <a href="{{ path('restaurant_delete', {'id':result.id}) }}" class="btn btn-default">Supprimer</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
    </div>
    <a class="btn-random" href="{{ path('restaurant_random') }}">Générer à nouveau</a>
</div>
{% endblock  %}

templates/searchBar.html.twig
<form class="d-flex" action="{{ path('restaurant_list') }}">
    <input
            type="search"
            name="q"
            value="{{ app.request.query.get('q') }}"
            class="searchBar"
            placeholder="Rechercher un restaurant...."
            aria-label="Search">
</form>

<div class="sortForm">
    <form method="GET" novalidate>
        <h2></h2>
        <div class="form-row">
            <label for="city"></label><select id="city" name="city" class="form-control-sort">
                    <option value="">Ville (toutes)</option>
                    {% for city in cities %}
                        <option value="{{ city.id }}">{{ city.name }}</option>
                    {% endfor %}
                </select>
            <label for="food"></label><select id="food" name="food" class="form-control-sort">
                    <option value="">Cuisine (toutes)</option>
                    {% for food in foods %}
                        <option value="{{ food.id }}">{{ food.name }}</option>
                    {% endfor %}
                </select>
            <div class="col_submit">
                <button type="submit" class="form-control-submit">Trier</button>
            </div>
        </div>
        <h2></h2>
    </form>
</div>

templates/userDetails.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
    <div class="block-page">
        <h1 class="block-name">Mon profil</h1>
        <h2 class="profil-name">{{user.email }}</h2>
        <div class="button">
            <a href="{{ path('user_update', {'id':user.id}) }}" class="btn-profil-update">Modifier</a>
            <a href="{{ path('user_delete', {'id':user.id}) }}" class="btn-profil-delete">Supprimer</a>
        </div>
        <div class="button">
            <a href="{{ path('app_logout') }}" class="btn-profil-logout">Se déconnecter</a>
        </div>
    </div>
{% endblock %}